### DISCUSSION TITLE
I cant link the folder in sonarr and others

### DISCUSSION THREAD

**Discussion by jflorido94** [Luctia/ezarr#54] [Help wanted] [answered]
**Describe the bug**
I just install it on my docker server, using the script and following the steps.
But I cant link the folder to foot folder on sonarr (and other) configuration

**To Reproduce**
1. Go to sonarr first configuration
2. Click on advance option
3. Scroll down to Root folder
4. See error on list of folders

**Expected behavior**
I expected all folders on the list

**Screenshots**
![image](https://github.com/user-attachments/assets/3b1f8160-f7c5-485c-a936-074cb2e8f7ae)
![image](https://github.com/user-attachments/assets/1a4d614a-dcf3-4195-b676-c1aeb02b1fca)

**System (please complete the following information):**
 - OS: Docker Container CT on proxmox
 - Browser Chrome

**Additional context**

**Comment by Luctia** [comment]
What does your docker-compose file look like?

**Reply by jflorido94** [reply]
```
name: ezarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/sonarr-config:/config
      - /var/lib/docker/volumens/plex/data:/data
    ports:
      - "7005:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/radarr-config:/config
      - /var/lib/docker/volumens/plex/data:/data
    ports:
      - "7006:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/lidarr-config:/config
      - /var/lib/docker/volumens/plex/data:/data
    ports:
      - "7007:8686"
    restart: unless-stopped

#  readarr:
#    image: lscr.io/linuxserver/readarr:develop
#    container_name: readarr
#    environment:
#      - PUID=${READARR_UID}
#      - PGID=13000
#      - UMASK=002
#      - TZ=Europe/Madrid
#    volumes:
#      - /var/lib/docker/volumens/plex/config/readarr-config:/config
#      - /var/lib/docker/volumens/plex/data:/data
#    ports:
#      - "8787:8787"
#    restart: unless-stopped

#  mylar3:
#    image: lscr.io/linuxserver/mylar3:latest
#    container_name: mylar3
#    environment:
#      - PUID=${MYLAR_UID}
#      - PGID=13000
#      - UMASK=002
#    volumes:
#      - /var/lib/docker/volumens/plex/config/mylar-config:/config
#      - /var/lib/docker/volumens/plex/data:/data
#    ports:
#      - "8090:8090"
#    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - user=13014:13000
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/audiobookshelf:/config
      - /var/lib/docker/volumens/plex/data/media/audiobooks:/audiobooks
      - /var/lib/docker/volumens/plex/data/media/podcasts:/podcasts
      - /var/lib/docker/volumens/plex/data/media/audiobookshelf-metadata:/metadata
    ports:
      - "7008:80"
    restart: unless-stopped

#  bazarr:
#    image: lscr.io/linuxserver/bazarr:latest
#    container_name: bazarr
#    environment:
#      - PUID=${BAZARR_UID}
#      - PGID=13000
#      - TZ=Europe/Madrid
#    volumes:
#      - /var/lib/docker/volumens/plex/config/bazarr-config:/config
#      - /var/lib/docker/volumens/plex/data/media:/media
#    ports:
#      - "6767:6767"
#    restart: unless-stopped

#  overseerr:
#    image: sctx/overseerr:latest
#    container_name: overseerr
#    environment:
#      - PUID=${OVERSEERR_UID}
#      - PGID=13000
#      - UMASK=002
#      - TZ=Europe/Madrid
#    volumes:
#      - /var/lib/docker/volumens/plex/config/overseerr-config:/app/config
#    ports:
#      - "5055:5055"
#    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=13012
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/jellyseerr-config:/app/config
    ports:
      - "7001:5055"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/prowlarr-config:/config
    ports:
      - "7002:9696"
    restart: unless-stopped
  
#  jackett:
#    image: lscr.io/linuxserver/jackett:latest
#    container_name: jackett
#    environment:
#      - PUID=${JACKETT_UID}
#      - PGID=13000
#      - UMASK=002
#      - TZ=Europe/Madrid    
#    volumes:
#      - /var/lib/docker/volumens/plex/config/jackett-config:/config
#    ports:
#      - 9117:9117
#    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    ports:
      - "7010:8191"
    restart: unless-stopped

#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    network_mode: host
#    environment:
#      - PUID=${PLEX_UID}
#      - PGID=13000
#      - VERSION=docker
#      - PLEX_CLAIM=${PLEX_CLAIM}
#    volumes:
#      - /var/lib/docker/volumens/plex/config/plex-config:/config
#      - /var/lib/docker/volumens/plex/data/media:/media
#    restart: unless-stopped

#  tautulli:
#    image: lscr.io/linuxserver/tautulli:latest
#    container_name: tautulli
#    # commented out because plex can also run outside of docker
#    #depends_on: 
#    #  - plex
#    environment:
#      - PUID=${UID}
#      - PGID=13000
#      - TZ=Europe/Madrid
#    volumes:
#      - /var/lib/docker/volumens/plex/config/tautulli-config:/config
#    ports:
#      - "8181:8181"
#    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/jellyfin-config:/config
      - /var/lib/docker/volumens/plex/data/media:/data
    ports:
      - "7000:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - /var/lib/docker/volumens/plex/config/qbittorrent-config:/config
      - /var/lib/docker/volumens/plex/data/torrents:/data/torrents
    ports:
      - "7003:8080"
      - "7004:6881"
      - "7004:6881/udp"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - /var/lib/docker/volumens/plex/config/sabnzbd-config:/config
      - /var/lib/docker/volumens/plex/data/usenet:/downloads
    ports:
      - "7011:8080"
    restart: unless-stopped
```
