### ISSUE TITLE
Add healthcheck dan autoheal to the docker compose files generated

### ISSUE THREAD

**Issue by phbrgnomo** [Luctia/ezarr#65]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add the following parameter to the servers on the docker-compose.yml file:

```
    healthcheck:
      test: ['CMD-SHELL', 'guacctl ping']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - autoheal=true
```
(This is an example of a guacamole container)

This make the containers send a signal about their health.

the `autoheal` tag link to another separated container:

```
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Necessário para monitorar os containers
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal  # Autoheal verifica containers com essa label
      - AUTOHEAL_INTERVAL=30  # Opcional: Verifica a cada 30 segundos (padrão é 5s)
      - AUTOHEAL_START_PERIOD=60  # Opcional: Aguarda 60s antes de começar (padrão é 0s)
```

This one fix any unhealthy container.

Pretty useful to quickly restart unhealthy containers

**Describe alternatives you've considered**

**Additional context**
