### ISSUE TITLE
How do you handle multiple media drives?

### ISSUE THREAD

**Issue by Miusaky** [Luctia/ezarr#9]
Nice project. Thanks for sharing it.

I have a few of these running in separate containers but as I'd like to add a few of the *arr services I'm considering replacing all of them with your setup here. 

The one point I'm a bit unsure of is how you handle multiple media disks? At the moment I have containers running on a small ssd and then multiple hdds which store the media. I assume most people with home servers have a similar setup. So unless you have one enourmous ssd I'm wondering:
- Do container performance not suffer on a hdd? 
- How do you add and structure other disks for media storage?

The current setup I have looks something like this:
Datadrive/docker/containers
Mediadrive1/film
Mediadrive2/tv
Mediadrive3/film
Mediadrive3/music

Since the current containers do not operate with one another all I had to do was include their drive paths in the dockercompose. With your setup I assume this would not work. Would you mind sharing an example of how I could handle this?

Thanks in advance.

**Comment by Luctia** [comment]
Note: this is a lot more involved than what I thought when I started typing this answer so please forgive any inconsistencies :)

Thanks for your interest! First off, regarding your questions:
- In principle, container performance will not be impacted by what you mount to it. Of course, the access speed to the media will be slower than if you had put that on your SSD, but like you said, that's not feasible.
- I assume you mean how you'd do this in this specific project, as you seem to understand how mounting drives to the host system works, so let's get into that.

This is a neat feature. In the future, I'd like to implement a CLI which could support multiple drives, but doing it now indeed requires some manual labour. What I would advise doing, for now, is removing the variables from `docker-compose.yml` and setting them to the specific paths you'd like. I _think_ it should work with the torrent client as well. Using only Sonarr and Radarr, that could look something like this:

```yml
---
version: "3.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - Datadrive/docker/jellyfin-config:/config
      - Mediadrive1/film:/media/film
      - Mediadrive2/tv:/media/tv
    ports:
      - 8096:8096
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - Datadrive/docker/radarr-config:/config
      - Mediadrive1/film:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - Datadrive/docker/sonarr-config:/config
      - Mediadrive2/tv:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - Datadrive/docker/qbittorrent-config:/config
      - Datadrive/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```
Now. I _think_ that should work and that it's not breaking anything that they don't share the same root directory, although it does look less neat. Along with this `docker-compose` comes a long list of permission hassle, but most of it is comparable to what is already in `setup.sh`

Depending on OS, you could also choose to mount a certain drive in a directory of your choosing. This might be the simplest way with the least modification to this repo. For example, mounting Media1 as `movies` in `data/media/`.

I'm not sure how ANY of this works in practice, I haven't tested it, but those are my thoughts :) Let me know what you discover!
